models/Pegawai.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pegawai".
 *
 * @property int $id_pegawai
 * @property int $id_personal
 * @property string $jenis_pegawai
 * @property string $status_pegawai
 * @property string $jabatan
 * @property string $tanggal_bergabung
 * @property int $gaji
 *
 * @property Personal $personal
 */
class Pegawai extends \yii\db\ActiveRecord
{
    const JENIS_PEGAWAI =  ['Medis' => 'Medis','Non Medis' => 'Non Medis'];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pegawai';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_personal', 'jenis_pegawai', 'status_pegawai', 'jabatan', 'tanggal_bergabung', 'gaji'], 'required'],
            [['id_personal', 'gaji'], 'integer'],
            [['tanggal_bergabung'], 'safe'],
            [['jenis_pegawai', 'status_pegawai', 'jabatan'], 'string', 'max' => 120],
            [['id_personal'], 'exist', 'skipOnError' => true, 'targetClass' => Personal::class, 'targetAttribute' => ['id_personal' => 'id_personal']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_pegawai' => 'Id Pegawai',
            'id_personal' => 'Id Personal',
            'jenis_pegawai' => 'Jenis Pegawai',
            'status_pegawai' => 'Status Pegawai',
            'jabatan' => 'Jabatan',
            'tanggal_bergabung' => 'Tanggal Bergabung',
            'gaji' => 'Gaji',
        ];
    }

    /**
     * Gets query for [[Personal]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPersonal()
    {
        return $this->hasOne(Personal::class, ['id_personal' => 'id_personal']);
    }


}

controllers/BerkasPegawaiController.php
<?php

namespace app\controllers;
use Yii;
use app\models\BerkasPegawai;
use app\models\Pegawai;
use app\models\BerkasPegawaiSearch;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * BerkasPegawaiController implements the CRUD actions for BerkasPegawai model.
 */
class BerkasPegawaiController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all BerkasPegawai models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new BerkasPegawaiSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BerkasPegawai model.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id_berkas_pegawai)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_berkas_pegawai),
        ]);
    }

    /**
     * Creates a new BerkasPegawai model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($id)
    {
      $pegawai = Pegawai::findOne($id);
        $model = new BerkasPegawai();
        
       
        // if ($this->request->isPost) {
            if ($model->load($this->request->post()) ) {
                if(!empty($_FILES['BerkasPegawai']['name']['file_berkas'])){
                    $file = UploadedFile::getInstance($model, 'file_berkas');
                    $berkas = $model->jenis_identitas.'-'.$id.'.'.$file->getExtension();
                    $model->file_berkas = $berkas;

                    $path = 'uploads/berkas_pegawai/';
                    if(!file_exists($path)){
                        FileHelper::createDirectory($path);
                    }
                    $file->saveAs($path.$berkas);

                }
                $model->id_pegawai =$pegawai->id_pegawai;
                 $model->tanggal_akhir_valid = date('Y-m-d', strtotime($model->tanggal_akhir_valid));
                $model->save();
                return $this->redirect(Yii::$app->request->referrer);
            }
            //buat grid data
            $searchModel = new BerkasPegawaiSearch();
            $dataProvider = $searchModel->search($this->request->queryParams);
            $dataProvider->query->andWhere(['id_pegawai' => $id]);
    
        // } else {
        //     $model->loadDefaultValues();
        // }

        return $this->render('create', [
            'model' => $model,
            'pegawai' => $pegawai,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Updates an existing BerkasPegawai model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
     public function actionUpdate($id_berkas_pegawai)
    {
        $model = $this->findModel($id_berkas_pegawai);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id_berkas_pegawai' => $model->id_berkas_pegawai]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing BerkasPegawai model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id_berkas_pegawai)
    {
        $this->findModel($id_berkas_pegawai)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the BerkasPegawai model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return BerkasPegawai the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id_berkas_pegawai)
    {
        if (($model = BerkasPegawai::findOne(['id_berkas_pegawai' => $id_berkas_pegawai])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PegawaiController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Pegawai;
use app\models\PegawaiSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Personal;

/**
 * PegawaiController implements the CRUD actions for Pegawai model.
 */
class PegawaiController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return [
    
                'access' => [
                    'class' => AccessControl::class,
                    'only' => ['update'],
                    'rules' => [
                        [
                            
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                    ],
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                
            ];
            
    }

    /**
     * Lists all Pegawai models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PegawaiSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pegawai model.
     * @param int $id_pegawai Id Pegawai
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id_pegawai)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_pegawai),
        ]);
    }

    /**
     * Creates a new Pegawai model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Pegawai();
        $namaPersonal = Personal:: getAllPersonal();
        
        if ($model->load(Yii::$app->request->post())) {
            $model ->tanggal_bergabung = \Yii::$app->formatter->asDate($model->tanggal_bergabung, 'yyyy-MM-dd');
            $model ->save();
            Yii::$app->session->setFlash('success', 'Data Berhasil Disimpan');
                return $this->redirect(['view', 'id_pegawai' => $model->id_pegawai]);
            } else {
                $model->loadDefaultValues();
            }
        

        return $this->render('create', [
            'model' => $model,
            'namaPersonal' => $namaPersonal
            
        ]);
    }

    /**
     * Updates an existing Pegawai model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id_pegawai Id Pegawai
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id_pegawai)
    {
        $model = $this->findModel($id_pegawai);
        $namaPersonal = Personal:: getAllPersonal();
        $model->tanggal_bergabung = date('d-M-Y', strtotime($model->tanggal_bergabung));
       // if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            if ($model->load(Yii::$app->request->post())) {
            $model ->tanggal_bergabung = Yii::$app->formatter->asDate($model->tanggal_bergabung, 'yyyy-MM-dd');
            $model->save();
            return $this->redirect(['view', 'id_pegawai' => $model->id_pegawai]);
        }

        return $this->render('update', [
            'model' => $model,
            'namaPersonal' => $namaPersonal
        ]);
    }

    /**
     * Deletes an existing Pegawai model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id_pegawai Id Pegawai
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id_pegawai)
    {
        $this->findModel($id_pegawai)->delete();
        Yii::$app->session->setFlash('danger', 'Data Berhasil Dihapus');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Pegawai model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id_pegawai Id Pegawai
     * @return Pegawai the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id_pegawai)
    {
        if (($model = Pegawai::findOne(['id_pegawai' => $id_pegawai])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/pegawai/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\select2\Select2;

/** @var yii\web\View $this */
/** @var app\models\Pegawai $model */
/** @var yii\widgets\ActiveForm $form */
?>

                        <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Data Pegawai</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                            <?php $form = ActiveForm::begin(); ?>
                            <div class ="row">
                            <div class="col-md-4">
                            <?= $form->field($model, 'id_personal')->widget(Select2::classname(), [
                                'data' => $namaPersonal,
                                'options' => ['placeholder' => 'Pilih Nama Lengkap...'],
                                // 'theme' => Select2::THEME_BOOTSRAP,
                                'pluginOptions' => [
                                'allowClear' => true
                                ],
                            ])->label('Nama Lengkap');
                            ?>
                            </div>

                            <div class="col-md-4">
                            <?= $form->field($model, 'jenis_pegawai')->widget(Select2::classname(), [
                                'data' => \app\models\Pegawai::JENIS_PEGAWAI,
                                'options' => ['placeholder' => 'Pilih  Jenis Pegawai...'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);?>
                            </div>

                          <div class="col-md-4">
                            <?= $form->field($model, 'status_pegawai')->widget(Select2::classname(), [
                                'data' => ['Pegawai Tetap' => 'Pegawai Tetap', 'Pegawai Kontrak'=> 'Pegawai Kontrak'],
                                'options' => ['placeholder' => 'Pilih  Status Pegawai...'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);?>
                            </div>
                            <div class="col-md-4">
                            <?= $form->field($model, 'jabatan')->textInput() ?>
                            </div>

                            <div class="col-md-4">
                            <?= $form->field($model, 'tanggal_bergabung')->widget(DatePicker::classname(), [
                                'options' => ['placeholder' => 'Pilih Tanggal ...'],
                                'pluginOptions' => [
                                    'autoclose' => true,
                                    'format' => 'dd-M-yyyy'
                                ]
                            ]);?>
                            </div>
                            <div class="col-md-4">
                            <?= $form->field($model, 'gaji')->textInput(['type' => 'number']) ?>
                            </div>
                            </div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
                        </div>
                        </div>              
</div>

views/pegawai/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\PegawaiSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="pegawai-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id_pegawai') ?>

    <?= $form->field($model, 'id_personal') ?>

    <?= $form->field($model, 'jenis_pegawai') ?>

    <?= $form->field($model, 'status_pegawai') ?>

    <?= $form->field($model, 'jabatan') ?>

    <?php // echo $form->field($model, 'tanggal_bergabung') ?>

    <?php // echo $form->field($model, 'gaji') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pegawai/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Pegawai $model */

$this->title = 'Create Pegawai';
$this->params['breadcrumbs'][] = ['label' => 'Pegawais', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pegawai-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'namaPersonal' => $namaPersonal
    ]) ?>

</div>

views/pegawai/index.php
<?php

use app\models\Pegawai;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;
/** @var yii\web\View $this */
/** @var app\models\PegawaiSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Pegawai';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pegawai-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Pegawai', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
          

           // 'personal.nama_lengkap',
           [
            'attribute' => 'nama_pegawai',
            'value' => function($model){
                return $model->personal->nama_lengkap;
            }
           ],
            [
                'attribute' => 'personal.jenis_kelamin',
                'headerOptions' => ['style' => 'width:140px'],
                'filter' => Html::activeDropDownList($searchModel, 'jenis_kelamin', \app\models\Personal::JENIS_KELAMIN,['class' => 'form-control', 'prompt' => 'Pilih'])
            ],
            // [
            //     'attribute' => 'alamat',
            //     'headerOptions' => ['style' =>'width:150px'],
            //     'value' => function($model){
            //         return $model->personal->alamat;
            //     }
            // ], 

            [
                'label' => 'Nomor KTP',
                'value' => function($model){
                    return $model->personal->no_ktp;
                }
            ],
            [
                
                'attribute' => 'jenis_pegawai',
                'headerOptions' => ['style' => 'width:140px'],
                'filter' => Html::activeDropDownList($searchModel, 'jenis_pegawai',\app\models\Pegawai::JENIS_PEGAWAI,['class' => 'form-control', 'prompt' => 'Pilih'])
            ],
            'attribute' => 'status_pegawai',
            
            'jabatan',
            'tanggal_bergabung',
            'gaji',
            [
                 'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Pegawai $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id_pegawai' => $model->id_pegawai]);
                 }
                 
            ],
            [
             
                
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['style' => 'width:65px'],
                'template' => '{berkas} ',
                'buttons' => [
                    // 'view'=> function($url, $model){
                    //     $url = Yii::$app->urlManager->createUrl(['pegawai/view','id' => $model->id_pegawai]);
                    //     return Html::a('<i class="glyphicon glyphicon-$iconname"</i>',$url,['title'=>'View']);
                    // },
                    // 'update'=> function($url, $model){
                    //     $url = Yii::$app->urlManager->createUrl(['pegawai/update','id' => $model->id_pegawai]);
                    //     return Html::a('<i class="glyphicon glyphicon-fas fa-user "</i>',$url,['title'=>'Update']);
                    // },
                    'berkas'=> function($url, $model){
                        $url = Yii::$app->urlManager->createUrl(['berkas-pegawai/create','id' => $model->id_pegawai]);
                        return Html::a('<i class="glyphicon glyphicon-fas fa-user "</i>',$url,['title'=>'Add File']);
                    },
                    // 'delete' => function($url, $model){
                    //     $url = Yii::$app->urlManager->createUrl(['pegawai/delete','id' => $model->id_pegawai]);
                    //     return Html::a('<i class="glyphicon glyphicon-fas fa-user"</i>',$url,['title'=>'Update',
                    //     'data-confirm'=> Yii::t('yii','Apakah yakin untuk menghapus data ini?'),
                    //     'data-method '=> 'post',
                    // ]);
                    // }
                ]
            ]
            ]
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/pegawai/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Pegawai $model */

$this->title = 'Update Pegawai: ' . $model->id_pegawai;
$this->params['breadcrumbs'][] = ['label' => 'Pegawais', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_pegawai, 'url' => ['view', 'id_pegawai' => $model->id_pegawai]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pegawai-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'namaPersonal' => $namaPersonal
    ]) ?>

</div>

views/pegawai/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Pegawai $model */

$this->title = $model->id_pegawai;
$this->params['breadcrumbs'][] = ['label' => 'Pegawais', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="pegawai-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id_pegawai' => $model->id_pegawai], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id_pegawai' => $model->id_pegawai], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_pegawai',
            'id_personal',
            'jenis_pegawai',
            'status_pegawai',
            'jabatan',
            'tanggal_bergabung',
            'gaji',
        ],
    ]) ?>

</div>