models/BerkasPegawai.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "berkas_pegawai".
 *
 * @property int $id_berkas_pegawai
 * @property int $id_pegawai
 * @property string $jenis_identitas
 * @property string $no_identitas
 * @property string|null $tanggal_akhir_valid
 *
 * @property Pegawai $pegawai
 */
class BerkasPegawai extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'berkas_pegawai';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_pegawai', 'jenis_identitas', 'no_identitas'], 'required'],
            [['id_pegawai'], 'integer'],
            [['tanggal_akhir_valid'], 'safe'],
            [['jenis_identitas'], 'string', 'max' => 30],
            [['no_identitas'], 'string', 'max' => 50],
            [['id_pegawai'], 'exist', 'skipOnError' => true, 'targetClass' => Pegawai::class, 'targetAttribute' => ['id_pegawai' => 'id_pegawai']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_berkas_pegawai' => 'Id Berkas Pegawai',
            'id_pegawai' => 'Id Pegawai',
            'jenis_identitas' => 'Jenis Identitas',
            'no_identitas' => 'No Identitas',
            'tanggal_akhir_valid' => 'Tanggal Akhir Valid',
        ];
    }

    /**
     * Gets query for [[Pegawai]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPegawai()
    {
        return $this->hasOne(Pegawai::class, ['id_pegawai' => 'id_pegawai']);
    }
}

controllers/BerkasPegawaiController.php
<?php

namespace app\controllers;
use Yii;
use app\models\BerkasPegawai;
use app\models\Pegawai;
use app\models\BerkasPegawaiSearch;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * BerkasPegawaiController implements the CRUD actions for BerkasPegawai model.
 */
class BerkasPegawaiController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all BerkasPegawai models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new BerkasPegawaiSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BerkasPegawai model.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id_berkas_pegawai)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_berkas_pegawai),
        ]);
    }

    /**
     * Creates a new BerkasPegawai model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($id)
    {
      $pegawai = Pegawai::findOne($id);
        $model = new BerkasPegawai();
        
       
        // if ($this->request->isPost) {
            if ($model->load($this->request->post()) ) {
                if(!empty($_FILES['BerkasPegawai']['name']['file_berkas'])){
                    $file = UploadedFile::getInstance($model, 'file_berkas');
                    $berkas = $model->jenis_identitas.'-'.$id.'.'.$file->getExtension();
                    $model->file_berkas = $berkas;

                    $path = 'uploads/berkas_pegawai/';
                    if(!file_exists($path)){
                        FileHelper::createDirectory($path);
                    }
                    $file->saveAs($path.$berkas);

                }
                $model->id_pegawai =$pegawai->id_pegawai;
                 $model->tanggal_akhir_valid = date('Y-m-d', strtotime($model->tanggal_akhir_valid));
                $model->save();
                return $this->redirect(Yii::$app->request->referrer);
            }
            //buat grid data
            $searchModel = new BerkasPegawaiSearch();
            $dataProvider = $searchModel->search($this->request->queryParams);
            $dataProvider->query->andWhere(['id_pegawai' => $id]);
    
        // } else {
        //     $model->loadDefaultValues();
        // }

        return $this->render('create', [
            'model' => $model,
            'pegawai' => $pegawai,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Updates an existing BerkasPegawai model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
     public function actionUpdate($id_berkas_pegawai)
    {
        $model = $this->findModel($id_berkas_pegawai);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id_berkas_pegawai' => $model->id_berkas_pegawai]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing BerkasPegawai model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id_berkas_pegawai)
    {
        $this->findModel($id_berkas_pegawai)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the BerkasPegawai model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id_berkas_pegawai Id Berkas Pegawai
     * @return BerkasPegawai the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id_berkas_pegawai)
    {
        if (($model = BerkasPegawai::findOne(['id_berkas_pegawai' => $id_berkas_pegawai])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/berkas-pegawai/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use kartik\file\FileInput;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var app\models\BerkasPegawai $model */
/** @var yii\widgets\ActiveForm $form */
?>

<!-- <div class="berkas-pegawai-form"> -->
                        <div class="card shadow mb-8">
                        <div class="card-header py-3">
                            <h6 class="m-13 font-weight-bold text-primary">Tambah Berkas Pegawai======================================List Berkas Pegawai</h6>
                            
                        </div>
                        
                        
                        <div class="row">
                            <div class="col-md-6">
                            <div class="card-body">
                            <div class="table-responsive">
                             <?php $form = ActiveForm::begin(); ?>
                             <div class ="row">
                            <div class="col-md-4">
                                <?= $form->field($pegawai, 'id_pegawai')->textInput(['value' => $pegawai->personal->nama_lengkap]) ?>
                            </div>

                              <div class="col-md-4">
                              <?= $form->field($model, 'jenis_identitas')->widget(Select2::classname(), [
                                'data' => ['KTP' => 'KTP', 'KK'=> 'KK', 'STR' => 'STR', 'SIK' => 'SIK', 'STR' => 'STR',
                                'SIK' => 'SIK', 'BPJS KESEHATAN' => 'BPJS KESEHATAN', 'BPJS KETENAGAKERJAAN' =>'BPJS KETENAGAKERJAAN', 'NPWP' => 'NPWP', 'SIPA' => 'SIPA', 'SIM' => 'SIM', 'SIP' => 'SIP',
                                'PASSPORT' => 'PASSPORT', 'LAIN-LAIN' => 'LAIN-LAIN' ],
                                'options' => ['placeholder' => 'Pilih  Status Pegawai...'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);?>
                            </div>
                           
                                <div class="col-md-4">
                              <?= $form->field($model, 'no_identitas')->textInput(['maxlength' => true]) ?>
                              </div>
                               <div class="col-md-4">
                            <?= $form->field($model, 'tanggal_akhir_valid')->widget(DatePicker::classname(), [
                                'options' => ['placeholder' => 'Pilih Tanggal Bergabung ...'],
                                'pluginOptions' => [
                                    'autoclose' => true,
                                    'format' => 'dd-M-yyyy'
                                ]
                            ]);?>
                            </div>
                            <div class="col-md-8">
                                 <?= $form->field($model, 'file_berkas')->widget(FileInput::classname(), [
                                        'options' => ['accept' => 'image/*', 'pdf/*'],
                                        'pluginOptions' => [
                                            'showUpload' => false,
                                            'allowedFileExtension' => ['jpeg', 'jpg', 'png', 'pdf'],
                                        ]
                                    ]);?>
                                 </div>
                             
                        </div>
                     </div>
             </div>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

                            </div>
                            <div class="col-md-6">
                            <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        // 'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table m-table', 'style' => 'font-size:11px'],
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            'id_berkas_pegawai',
                            'id_pegawai',
                            'jenis_identitas',
                            'no_identitas',
                            'tanggal_akhir_valid',
                            'file_berkas',
                            // [
                            //    'header' => 'Aksi',
                            //    'class' => 'yii\grid\ActionColumn',
                            //  'headerOptions' => ['style' => 'width:80px'],
                            //    'template' => '{delete}',
                            //    'delete'=> function($url, $model){
                            //     $url = Yii::$app->urlManager->createUrl(['berkas-pegawai/delete','id' => $model->id_pegawai]);
                            //     return Html::a('<i class="glyphicon glyphicon-trash "</i>',$url,['title'=>'Delete',
                            //       'data-confirm ' =>Yii::t('yii', 'Apakah yakin ingin menghapus dta ini?'),
                            //       'data-method' => 'post',
                            
                            //     ]);
                            // },
                                //   [ 'class' => 'yii\grid\ActionColumn'],
                                // }
                            ],
                        ],
                    ); ?>
                        </div>
                     
                     
    </div>

views/berkas-pegawai/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\BerkasPegawaiSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="berkas-pegawai-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id_berkas_pegawai') ?>

    <?= $form->field($model, 'id_pegawai') ?>

    <?= $form->field($model, 'jenis_identitas') ?>

    <?= $form->field($model, 'no_identitas') ?>

    <?= $form->field($model, 'tanggal_akhir_valid') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/berkas-pegawai/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\BerkasPegawai $model */

$this->title = 'Create Berkas Pegawai';
$this->params['breadcrumbs'][] = ['label' => 'Berkas Pegawais', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="berkas-pegawai-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
         'pegawai' => $pegawai,
         'dataProvider' => $dataProvider
        
    ]) ?>

</div>

views/berkas-pegawai/index.php
<?php

use app\models\BerkasPegawai;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;
/** @var yii\web\View $this */
/** @var app\models\BerkasPegawaiSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Berkas Pegawais';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="berkas-pegawai-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Berkas Pegawai', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_berkas_pegawai',
            'id_pegawai',
            'jenis_identitas',
            'no_identitas',
            'tanggal_akhir_valid',
            'file_berkas',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, BerkasPegawai $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id_berkas_pegawai' => $model->id_berkas_pegawai]);
                 }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/berkas-pegawai/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\BerkasPegawai $model */

$this->title = 'Update Berkas Pegawai: ' . $model->id_berkas_pegawai;
$this->params['breadcrumbs'][] = ['label' => 'Berkas Pegawais', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_berkas_pegawai, 'url' => ['view', 'id_berkas_pegawai' => $model->id_berkas_pegawai]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="berkas-pegawai-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/berkas-pegawai/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\BerkasPegawai $model */

$this->title = $model->id_berkas_pegawai;
$this->params['breadcrumbs'][] = ['label' => 'Berkas Pegawais', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="berkas-pegawai-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id_berkas_pegawai' => $model->id_berkas_pegawai], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id_berkas_pegawai' => $model->id_berkas_pegawai], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_berkas_pegawai',
            'id_pegawai',
            'jenis_identitas',
            'no_identitas',
            'tanggal_akhir_valid',
        ],
    ]) ?>

</div>